# TRMNLP configuration
# {{ env.VARIABLE }} interpolation is available here
---
# auto-reload when files change (`watch: false` to disable)
watch:
  - .trmnlp.yml
  - src

# values of custom fields (defined in src/settings.yml)
custom_fields: {
  pixelfed_base_url: https://photos.yeargin.social,
  pixelfed_api_key: '{{ env.PIXELFED_API_KEY }}',
  pixelfed_layout: '4col_x_2row',
  pixelfed_tag: '#landscape',
  pixelfed_object_fit: cover
}

# override variables
variables:
  trmnl: {
    plugin_settings: {
      instance_name: 'Pixelfed'
    }
  }
